POST http://localhost:3001/register
Content-Type: application/json

{
  "username": "bhanu123",
  "name": "Adam Richard",
  "password": "bhanu143",
  "gender": "male",
  "location": "Detroit"
}


###
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "bhanu123",
  "password": "bhanu143"
}


###
PUT http://localhost:3001/change-password
Content-Type: application/json

{
  "username": "chandu123",
  "oldPassword": "chandu143",
  "newPassword": "chandu111"
}